import os
import uvicorn
import logging

from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from dotenv import load_dotenv
from RAG_mqr import answer_with_rag # Import RAG pipeline function

from src.backend.pydantic_models import ResearchPaperQuery

load_dotenv()

if "OPENAI_API_KEY" not in os.environ:
    raise EnvironmentError("openai key not set in environment.")

app = FastAPI()
app.mount('/files', StaticFiles(directory=".", html=True), name="static")
logger = logging.getLogger('uvicorn.error')


# Handles research queries.
@app.post('/rag_pipeline', summary="Submit a research query", description="Returns an answer generated by the RAG pipeline.")
async def ask_rag_pipeline(query_request:ResearchPaperQuery):
    try:
        logging.info("Successfully called RAG pipeline endpoint")
        # answer = answer_with_rag.invoke(query_request.message)
        return {"answer": None}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    
if __name__ == "__main__":
    uvicorn.run("app_rag:app", host="localhost", port=8002, reload=True)
