# Use the official Python 3.11 slim image as a base
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the entire monorepo into the container
COPY requirements.txt requirements.txt

# Install Python dependencies for the backend
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .

# Make the start script executable
RUN chmod +x start-test.sh

# Start the processes using the start script
CMD ["bash", "start-test.sh"]
